[server]
# exit session if no requests were received during given period
timeout = 1800 # 30 minutes

[[semantic_tokens]]
token = "keyword"
face = "blue"

[[semantic_tokens]]
token = "function"
face = "yellow"

[[semantic_tokens]]
token = "type"
face = "yellow"

[[semantic_tokens]]
token = "string"
face = "green"

[[semantic_tokens]]
token = "string"
face = "green"

[[semantic_tokens]]
token = "type"
face = "green"
modifiers = ["namespace"]

[[semantic_tokens]]
token = "builtin"
face = "magenta"

# [[semantic_tokens]]
# token = "operator"
# face = "red"

[language.zig]
filetypes = ["zig"]
roots = ["build.zig"]
command = "/home/luuk/dev/zls/zig-cache/bin/zls"

[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "/home/luuk/go/bin/gopls"
offset_encoding = "utf-8"
