[server]
# exit session if no requests were received during given period
timeout = 1800 # 30 minutes

[semantic_tokens]
#tagField = "function"
#errorTag = "function"
#field = "function"
# parameter = "variable"
type = "type"
# variable = "variable"
#namespace = "module"
function = "function"
# string = "string"
keyword = "keyword"
#operator = "operator"
#comment = "comment"

[semantic_token_modifiers]
namespace = "module"

[language.zig]
filetypes = ["zig"]
roots = ["build.zig"]
command = "/home/luuk/dev/zls/zig-cache/bin/zls"

[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "/home/luuk/go/bin/gopls"
offset_encoding = "utf-8"
